#!/bin/sh
python train_models.py --item_family GROCERY_I
python train_models.py --item_family CLEANING
python train_models.py --item_family BREAD_BAKERY
python train_models.py --item_family DELI
python train_models.py --item_family POULTRY
python train_models.py --item_family EGGS
python train_models.py --item_family PERSONAL_CARE
python train_models.py --item_family LINGERIE
python train_models.py --item_family BEVERAGES
python train_models.py --item_family AUTOMOTIVE
python train_models.py --item_family DAIRY
python train_models.py --item_family GROCERY_II
python train_models.py --item_family MEATS
python train_models.py --item_family FROZEN_FOODS
python train_models.py --item_family HOME_APPLIANCES
python train_models.py --item_family SEAFOOD
python train_models.py --item_family PREPARED_FOODS
python train_models.py --item_family LIQUOR_WINE_BEER
python train_models.py --item_family BEAUTY
python train_models.py --item_family HARDWARE
python train_models.py --item_family LAWN_AND_GARDEN
python train_models.py --item_family PRODUCE
python train_models.py --item_family HOME_AND_KITCHEN_II
python train_models.py --item_family HOME_AND_KITCHEN_I
python train_models.py --item_family MAGAZINES
python train_models.py --item_family HOME_CARE
python train_models.py --item_family PET_SUPPLIES
python train_models.py --item_family BABY_CARE
python train_models.py --item_family SCHOOL_AND_OFFICE_SUPPLIES
python train_models.py --item_family PLAYERS_AND_ELECTRONICS
python train_models.py --item_family CELEBRATION
python train_models.py --item_family LADIESWEAR
python train_models.py --item_family BOOKS
